### ISSUE TITLE
Added a commit code to have Boron have OpenMV send information.

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron#8] opened 2023-10-04 15:31 UTC

**Comment by BentleySettin** [comment] 2023-10-04 15:36
I added code to the commit list under the project Boron. It's purpose is to have the Boron tell the openMV to send it information when the Boron wants.

**Comment by SUPScientist** [comment] 2023-10-04 17:03
Great, I look forward to reviewing the new code. Please use one of the two following options to provide us with more information. 
1. Provide a link to the relevant commit. You can do this by clicking from the main repository page where it shows the seven-character commit hash (in this case, d5ba7f5) and copying and pasting the full link to that page here. Here's a screenshot of where to find it. 
<img width="1135" alt="image" src="https://github.com/TinyCamML/Boron/assets/7882374/a32a64f9-48fb-446b-a3b4-19b2a2a625d8">
2. If you want us to drill in even deeper, use the technique Evan demoed on our zoom call and copy and paste the permalink to the specific lines of code that you want us to review.

**Comment by SUPScientist** [comment] 2023-10-04 17:04
Since there are only three commits, it's easy for me to identify which one to look at, but once the codebase/repository grows, it will be increasingly difficult. 

I'll answer my own question using option #1 from above to show you what I mean. Here is the relevant commit that you are asking us to review: https://github.com/TinyCamML/Boron/commit/d5ba7f5abb21bff19b69c760a9e993073e912bf7.

**Comment by SUPScientist** [comment] 2023-10-04 17:15
As a more direct reply to the initial question, your new code won't compile or work. The code through line 16 is Particle/Wiring code. That is what gets compiled and then flashed onto the Boron. Lines 19–end are written in something intended to be (micro)python. That is what gets compiled and flashed onto the openMV. You cannot have code for two distinct devices in one single file. First, it won't compile (because you're using two totally different languages). Second, even if it did compile, it would only get flashed to the Boron. 

Instead, create a single file of code just for the Boron. Edit your current .ino file, recommit, push, etc., and ask for another review as needed.

**Comment by SUPScientist** [comment] 2023-10-04 17:16
@ebgoldstein, no need for a code review yet unless you care to take a peek but tagging you here in case you want to follow along, comment on GitHub usage, etc.

**Comment by BentleySettin** [comment] 2023-10-04 21:00
Okay! I will look more into the code. 

As you can tell I made the commit messier and am struggling how to rename the the descriptive portion of the commit. I renamed it entirely but the second part is lengthy and says "update and rename".

**Comment by BentleySettin** [comment] 2023-10-04 21:04
https://github.com/TinyCamML/Boron/commit/2e863923fde9e68879d1c9c458decb0c8631e5cc 

I am just practicing giving you the direct commit.

**Comment by ebgoldstein** [comment] 2023-10-09 14:29
see also: 
https://docs.openmv.io/openmvcam/tutorial/openmvide_overview.html#tools

**Comment by BentleySettin** [comment] 2023-10-10 16:27
Thank you Evan! I will check out this link too.

**Comment by BentleySettin** [comment] 2023-10-11 13:33
The code in https://github.com/TinyCamML/Boron/commit/0f5ef2eed6e563b884bf1c361af5c895290d21a5 has been updated. It is in VS code and successfully asks OpenMV for either "Flood" or "No Flood". 

Dr. Bresnahan and I chatted yesterday but it seems to recieve data that is a conjumbled mess of mixed of askey. After added delays and serial close and open it has cleaned up to sending just a blank line.

**Comment by BentleySettin** [comment] 2023-10-11 13:34
The only code I added to openMV was "uart.write()" for flood and no flood.

**Comment by SUPScientist** [comment] 2023-10-11 14:36
It's "ASCII": https://www.w3schools.com/charsets/ref_html_ascii.asp.

Can you confirm that the OpenMV is doing what you think it is? If so, how? Does it serial print (over USB) to computer screen "flood" or "no flood"? 

After confirming that, what are you doing to troubleshoot the incorrect ASCII translation on the Boron side?

**Comment by SUPScientist** [comment] 2023-10-11 16:28
This sounds like an appropriate troubleshooting approach. 

I understand what you mean that you cannot yet confirm that the OpenMV is sending data as hoped. To restate that question, *how* could you determine that it is doing what you want? E.g., without worrying about what the Boron is doing, can you prove that you can print "Flood" or "No Flood" to the OpenMV's serial monitor via USB? Is there a uart.print or just the uart.write?

**Comment by BentleySettin** [comment] 2023-10-12 13:40
I found the serial monitor option on the bottom of OpenMV. It has been there all along but because I wasn't working in full screen I never saw it.

I am running the camera and I have continually recieved the message: 

Traceback (most recent call last):
  File "main.py", line 3, in <module>
Exception: IDE interrupt

I am trying to figure out why this is occurring. Line 3 is https://github.com/TinyCamML/OMVmodel/blob/628c58bbc829f9c162b2ab7f652e225012f65835/FloodCamMLpy.py#L3

**Comment by ebgoldstein** [comment] 2023-10-12 13:46
Try breaking that line up into all the separate import commands

import pyb
import tf
...

Then rerun and it will identify the line

**Comment by BentleySettin** [comment] 2023-10-12 13:51
I did this and now it is saying:

Traceback (most recent call last):
  File "main.py", **line 2**, in <module>
Exception: IDE interrupt

And line 2 has no information on it. Based on scoping around the internet an openMV docs it is possibly and IDE problem, not code issue. I updated all firmware and IDE.

**Comment by BentleySettin** [comment] 2023-10-12 13:55
A few typos in that last comment:
 
And line 2 has no information on it. Based on scoping around the internet and openMV docs it is possibly an IDE problem, not code issue. I updated all firmware and IDE.

**Comment by ebgoldstein** [comment] 2023-10-13 15:21
hmm.. can you test on a different computer just to rule out an IDE issue?

**Comment by SUPScientist** [comment] 2023-10-13 18:02
An IDE issue isn't my first guess. Weren't you successfully flashing code last week, Bentley, as verified by the streaming camera imagery in the IDE window? If you had anything running that you flashed, it's highly unlikely to be an IDE issue. 

Can you commit/push your updated code following Evan's recommended edits above so we can take a look at what you're currently using?

**Comment by BentleySettin** [comment] 2023-10-14 16:16
I have successfully streamed camera imagery from the IDE window. I can retry it again when I come back in to make sure it is still working and not an IDE issue. 

I will commit an updated code.

**Comment by SUPScientist** [comment] 2023-10-17 19:05
Confirming that we've seen multiple built-in examples and our own blink_LED.py code run, both via the IDE and via saving as main.py and running while disconnected from PC. IDE does not appear to be the main issue. 

Issue seems to be with `tf.load()` statement (not finding the .tflite file). 

Recommend reading more from getting started guide and `tf.load()` examples for openmv.

**Comment by SUPScientist** [comment] 2023-10-17 19:18
Exciting update (cc @ebgoldstein): .tflite is now loading. Serial monitor shows flood/no flood, so toy code is working as hoped. 

For future reference, the problem seemed to be with way .tflite was downloaded from GitHub and/or modified in Windows Explorer prior to dragging into the OpenMV's drive. When we redownloaded .tflite file, dragged it into the OpenMV drive without any renaming/modification, and added the new name ('MNv2Flood_cat (4).tflite') to the main.py file, it operated as expected.

NB: this thread has diverged a bit from the main issue, so not closing, but let's get back to the OpenMV<—>Boron comms now.

**Comment by ebgoldstein** [comment] 2023-10-17 19:19
aha!

**Comment by ebgoldstein** [comment] 2023-10-17 19:20
if you want to meet at all to discuss anything, i am free RN (until 4:35pm)

**Comment by SUPScientist** [comment] 2023-10-17 19:26
I'm bouncing into two back-to-back meetings starting in 5, but @BentleySettin, maybe a good idea if you're planning on being in the lab a bit longer?

**Comment by SUPScientist** [comment] 2023-10-27 14:05
Closing as duplicate of https://github.com/TinyCamML/Boron/issues/12, but @ebgoldstein, as our GH teacher, feel free to jump in and suggest a different workflow for any of this if needed, please!

**Closed by SUPScientist** 2023-10-27 14:05 UTC
Labels: enhancement, help wanted
